version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/server
hooks:
  BeforeInstall:
    - location: /before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: /after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /application_start.sh
      timeout: 300
      runas: ubuntu
